### ISSUE TITLE
Mouse cursor on desktop ugly X

### ISSUE THREAD

**Issue by onli** [BurntSushi/wingo#128]
Wingo does not seem to set a proper mouse type. When hovering over the desktop background or over programs that do not set the mouse cursor to a specific type, the cursor becomes an X instead of the default pointed arrow.

See this screenshot:

![wingo](https://cloud.githubusercontent.com/assets/900380/19417045/57d34ed6-93a2-11e6-8c09-276e130f9d21.jpg)

The black X should be the default mouse arrow.

**Comment by BurntSushi** [comment]
> Wingo does not seem to set a proper mouse type.

Indeed it does not, and it never will. Wingo is a WM, not a DE, so it doesn't mess with orthogonal settings. You can set your own cursor pretty easily with:

```
xsetroot -cursor_name left_ptr
```

Which can be run before or after Wingo starts.

**Comment by onli** [comment]
Thanks for showing the command. Please be aware though that other WMs do set the proper default cursor, to my knowledge it is Wingo which is the exception here. DE or not, it makes for a worse first experience, which is a pity.

**Comment by BurntSushi** [comment]
I haven't really kept up on what other WMs are doing, and I can appreciate that it may be shocking to some users. Maybe we can add a note in the README.

The "problem" with setting a default cursor is that there is no default cursor. Who says `left_ptr` is it? That means that if Wingo sets the default cursor, we also need an option to to disable that behavior or to at least change the default setting. It's a lot of extra work that I'm honestly not particularly interested in doing. Sorry.

**Comment by onli** [comment]
I understand. Without wanting to test your patience: Maybe this would be something that could be added as a default startup hook, like the easter egg? That would be easy enough to disable, and advanced users will check that file anyway. But I would understand if you don't want to move settings-like stuff into there, and xsetroot is not always installed.

If not, would it be helpful if I make a PR with a small note in the INSTALL?

>  there is no default cursor. Who says left_ptr is it?

I do ;) No, really, I'm pretty sure left_ptr is default in every DE and WM I every saw, including Windows and OSX, maybe apart from one or two small WMs that as well falls back to not defining a default.

**Comment by BurntSushi** [comment]
A note in the INSTALL is about as far as I'm willing to go. As you can probably tell, most Wingo development has stopped because it's in a state that I'm pretty happy with. I was never able to figure out how to scale up development to deal with the issue tracker. There are no tests and there's no easy way to add them at this point, so it's essentially impossible to do much more work at this point without very significant rampup and QA time.

> I do ;) No, really, I'm pretty sure left_ptr is default in every DE and WM I every saw, including Windows and OSX, maybe apart from one or two small WMs that as well falls back to not defining a default.

You're conflating "the default everywhere else" and "the actual default." For example, I know a few people who use a mouse left handed. They might want `right_ptr`. Which means the default is wrong and there has to be a way to change it.

I suppose going the route of the easter egg is a possibility, but honestly, I think the problem here is pretty vastly overstated.

**Comment by ddan39** [comment]
FYI, Wingo is NOT the exception. Many standalone WMs I have used do not set
the cursor. I would actually be willing to bet that setting it is less
common for standalone WMs.
