### ISSUE TITLE
[enhancement] Automatically create sufficient workspaces for number of displays

### ISSUE THREAD

**Issue by whereswaldon** [BurntSushi/wingo#132]
I changed my configuration so that I only start with one workspace (I'm on a laptop, so I don't need much more than that), but later plugged in an external monitor and started wingo. It crashed because there were more displays than workspaces. Adding a second default workspace solved the problem in the config. Couldn't wingo automatically add numbered workspaces if there aren't enough to give one to each display? Sorry if this is actually really hard/annoying. I have little knowledge of window manager internals.

**Comment by BurntSushi** [comment]
Wingo could. But I don't see any compelling reason to fix this.

**Comment by whereswaldon** [comment]
It's really jarring to plug in a monitor and then be unable to start your window manager without editing the config. Would you be opposed to this functionality being added by someone else as a PR? Or do you just have no interest in this functionality whatsoever?

**Comment by BurntSushi** [comment]
I'm not sure if you noticed, but this project hasn't had any new features in a long time. It is essentially in maintenace mode. I would mention it in the README.

The problem is that I never wrote any automated tests. So the only way for me to accept a PR is to thoroughly test and QA it manually. It is not scalable.

Just make sure you have enough workspaces before configuring a new monitor.

**Comment by whereswaldon** [comment]
Ah, I see. I agree that it would be nice for that to be in the README. I figured that it probably was an issue with your available free time, but this makes more sense.

Just so you know, you did fantastic work. I love wingo. I've been using it for four months now, and that monitor thing is the *only* thing about it that seemed worth mentioning as an issue. Thanks for creating it!
