### ISSUE TITLE
Desktop not redrawing on virtual desktop switch in KDE

### ISSUE THREAD

**Issue by glatteis** [BurntSushi/wingo#140]
When I switch the virtual desktop in KDE, and move into a desktop that is empty, what happens is that I see the frame that was drawn before I switched (the windows on the other desktops frozen), what should happen is that I see the desktop background.

**Comment by glatteis** [comment]
![image](https://user-images.githubusercontent.com/8374054/56469631-8e510300-643c-11e9-8148-030a186c258c.png)
Just discovered this is not limited to desktop switching, probably some trivial setting I haven't set.

**Comment by BurntSushi** [comment]
It's unlikely that this is a problem with Wingo specifically. I don't know what the solution is. You might consider running a standalone compositor, such as compton.

Also, while I haven't looked into it for many years now, Wingo didn't work too well with KDE or other desktop environments. Following the EWMH and ICCCM standards likely isn't enough any more.

Otherwise, please note that, as the README states, this repository is in maintenance mode. It's unlikely that even if this bug is in Wingo, that it will be fixed, unless the fix is trivial.

**Comment by glatteis** [comment]
Thanks, running compton indeed fixes this.
Wingo works great with xfce, by the way. I use it as my daily driver :)
